name: Build and Deploy ITS_LIVE Monitoring

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
  workflow_run:
    workflows:
      - "Tag New Version"
    branches:
      - main
    types:
      - completed

jobs:
  call-version-info-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-version-info.yml@v0.20.0
    permissions:
      contents: read
    with:
      python_version: '3.12'

  dockerize:
    needs: call-version-info-workflow
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ needs.call-version-info-workflow.outputs.version_tag }}
      cancel-in-progress: true
    permissions:
      contents: read
    env:
      ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
      VERSION_TAG: ${{ needs.call-version-info-workflow.outputs.version_tag }}
    outputs:
      image_uri: ${{ steps.push.outputs.image_uri }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - run: make install

      - name: Lowercase repository for container registry
        run: |
          echo "ECR_REPOSITORY=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: build image
        run: |
          make image

      - name: push image
        id: push
        if: ${{ ! github.event.pull_request.head.repo.fork }}
        run: |
          docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${VERSION_TAG}
          echo "image_uri=${ECR_REGISTRY}/${ECR_REPOSITORY}:${VERSION_TAG}" >> $GITHUB_OUTPUT

      - name: Add test tag
        if: ${{ github.event_name != 'pull_request' && contains(env.VERSION_TAG, '.dev') }}
        uses: akhilerm/tag-push-action@v2.2.0
        with:
          src: ${{ vars.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.VERSION_TAG }}
          dst: ${{ vars.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:test

      - name: Add latest tag
        if: ${{ github.event_name != 'pull_request' && ! contains(env.VERSION_TAG, '.dev') }}
        uses: akhilerm/tag-push-action@v2.2.0
        with:
          src: ${{ vars.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.VERSION_TAG }}
          dst: ${{ vars.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ vars.ECR_REGISTRY }}


  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    concurrency:
      group: deploy-${{ github.ref == 'refs/heads/main' && 'prod' || 'test' }}
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'test' }}
    runs-on: ubuntu-latest
    needs:
      - dockerize
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: ./.github/actions/deploy
        with:
          STACK_NAME: ${{ vars.STACK_NAME }}
          EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
          EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
          CF_TEMPLATE_BUCKET: cf-templates-3o5lnspmwmzg-us-west-2
          LANDSAT_TOPIC_ARN: ${{ vars.LANDSAT_TOPIC_ARN }}
          SENTINEL2_TOPIC_ARN: ${{ vars.SENTINEL2_TOPIC_ARN }}
          HYP3_API: ${{ vars.HYP3_API }}
          HYP3_JOBS_TABLE: ${{ vars.HYP3_JOBS_TABLE }}
          LAMBDA_LOGGING_LEVEL: INFO
          PUBLISH_BUCKET: ${{ vars.PUBLISH_BUCKET }}
          MATTERMOST_PAT: ${{ secrets.MATTERMOST_PAT }}
          ECR_IMAGE_URI: ${{ needs.dockerize.outputs.image_uri }}
